### ISSUE TITLE
Preserve select helpers when translating to YAML

### ISSUE THREAD

**Issue by emilyriederer** [rstudio/pointblank#232]
## Prework

- [x] Read and abide by **pointblank**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rich-iannone/pointblank/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rich-iannone/pointblank/issues) (both open and closed).

## Proposal

Currently, YAML translation functions evaluate the select helpers and record the specific realizations in the dataset. For example, in the following reprex, I configure the check with `starts_with("date")` but the resulting YAML file instead shows the check specifically for the variables `date` and `datetime` which match the helper. 

``` r
library(pointblank)

agent <- 
  create_agent(read_fn = ~small_table) %>%
  col_is_date(starts_with("date"))

yaml_agent_string(agent)
```

    #> read_fn: ~small_table
    #> tbl_name: .na.character
    #> label: '[2020-11-18|17:45:00]'
    #> locale: en
    #> steps:
    #> - col_is_date:
    #>     columns: vars(date_time)
    #> - col_is_date:
    #>     columns: vars(date)

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To support a "roundtrip" or to support greater portability of config files (e.g. use the same YAML file to validate multiple tables; or continue to use a YAML file as columns are added to a table), it would be more helpful to preserve the select helpers in the YAML, e.g

    #> steps:
    #> - col_is_date:
    #>     columns: starts_with("date")

This is related to #218 in that it supports a round-trip. However, I'm opening a new issue since this is a specific feature besides the tests, and @rich-iannone suggested I open an issue on discussion.

**Comment by rich-iannone** [comment]
Thank you Emily for submitting this issue. Major oversight on my part (I preserved the `vars()` but nothing else) but I think this will make for a higher fidelity round trip. Tests that will be added for #218 will include this work as well.

**Comment by emilyriederer** [comment]
Hey @rich-iannone - thank you so much for implementing this feature. I just got a chance to try it out, and it's great. I did notice just one thing about the "round tripping" and was curious of your thoughts.  

Right now, the tidyselect helpers are preserved *if they hit on any checks*. So, for example, in the block below I have variables in my dataset that start with `x` so the YAML appropriately contains a check on `columns: starts_with("x")`. 

However, if there are checks in the pipeline that the sample dataset does *not* trigger, they do not make it to the YAML. Below, this is show that the check on variables starting with `z` is not written to YAML because it's not in the sample data. This could potentially make the files less "portable" between projects. 

I recognize this may be an incredibly niche problem only related to my "off-label" use case (to steal a phrase from Hadley's rstudio::global keynote). I also have a work-around that I'm totally happy with (I just generate a fake dataframe with all the column types I need). I just thought I'd document in case it was a corner case that would be of interest. 

Thanks again for all your work on this great package!

``` r
library(pointblank)
tmpdir <- tempdir()
tmp <- gsub("////", "", tempfile(tmpdir = "", fileext = ".yml"))

create_agent(read_fn = ~data.frame(x_1 = 1, x_2 = 2, y_1 = 3)) %>%
  col_vals_gt(starts_with("x"), 10, step_id = 1) %>%
  col_vals_lt(starts_with("z"),  2, step_id = 2) %>%
  yaml_write(filename = tmp, path = tmpdir)

cat(readLines(file.path(tmpdir, tmp)), sep = "\n")
```

    #> read_fn: ~data.frame(x_1 = 1, x_2 = 2, y_1 = 3)
    #> tbl_name: ~
    #> label: '[2021-02-09|06:03:29]'
    #> locale: en
    #> steps:
    #> - col_vals_gt:
    #>     columns: starts_with("x")
    #>     value: 10.0

<sup>Created on 2021-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

-----

title: reprex\_reprex.R
author: emily
date: ‘2021-02-09’

-----

**Comment by rich-iannone** [comment]
@emilyriederer  I think you uncovered an issue that occurs well before the YAML generation code path. The `col_vals_lt(starts_with("z"),  2, step_id = 2)` step is not even being registered as a validation step because the tidyselect evaluation turning up no columns (this might even be a bug in pointblank; I don't currently know why the registration isn't happening). 

This lack of validation step registration is actually not a good thing at all! The data can change from one interrogation to the next so it's unreasonable to disallow steps based on the data. Besides that, if you add a step it should always be added unless you made a serious input error.

Could you please open a new issue about this? The main issues are:

(1) the evaluation of expressions in `columns` should occur during rule creation
(2) the re-evaluation of expressions in `columns` should happen again during interrogation
(3) handle cases where no column is available during interrogation (i.e., skips the step but preserves it, unlike now)
(4) the expansion of validation steps might need to be reconsidered (e.g., step 1 that targets 3 columns might be resolved as steps 1.1, 1.2, and 1.3 in the reporting)

This would require some pretty big changes in lots of areas of the package but I think it's the right approach.

**Comment by emilyriederer** [comment]
Thanks for the detailed reply, @rich-iannone ! It's interesting to understand more about what is happening under the hood. Again, I doubt if this is a huge deal in most use cases that are less strange than my own, so no pressure from me, but per your request I opened #275 to continue the discussion here.

**Comment by rich-iannone** [comment]
@emilyriederer thanks so much for creating that new issue! I hope to work on it soon.
